const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  chooseFolder: () => ipcRenderer.invoke('choose-folder'),
  chooseFile: (filters) => ipcRenderer.invoke('choose-file', filters),
  defaultDownloads: () => ipcRenderer.invoke('default-downloads'),
  openPath: (p) => ipcRenderer.invoke('open-path', p),
  showInFolder: (p) => ipcRenderer.invoke('show-in-folder', p),
  binaryStatus: () => ipcRenderer.invoke('binary-status'),
  autoLaunchGet: () => ipcRenderer.invoke('autolaunch-get'),
  autoLaunchSet: (v) => ipcRenderer.invoke('autolaunch-set', v),

  probeUrl: (url) => ipcRenderer.invoke('probe-url', url),
  startDownload: (opts) => ipcRenderer.invoke('start-download', opts),
  convertFile: (opts) => ipcRenderer.invoke('convert-file', opts),
  compressFile: (opts) => ipcRenderer.invoke('compress-file', opts),
  cancelJob: (jobId) => ipcRenderer.invoke('cancel-job', jobId),
  downloadThumbnail: (opts) => ipcRenderer.invoke('download-thumbnail', opts),
  removeBackground: (opts) => ipcRenderer.invoke('remove-background', opts),
  fileToDataUrl: (p) => ipcRenderer.invoke('file-to-data-url', p),
  saveClipboardImage: (data) => ipcRenderer.invoke('save-clipboard-image', data),
  upscaleImage: (opts) => ipcRenderer.invoke('upscale-image', opts),
  ocrImage: (opts) => ipcRenderer.invoke('ocr-image', opts),
  transcribeAudio: (opts) => ipcRenderer.invoke('transcribe-audio', opts),
  pickColor: () => ipcRenderer.invoke('pick-color'),
  pickerSubmit: (data) => ipcRenderer.send('picker-submit', data),
  compressImage: (opts) => ipcRenderer.invoke('compress-image', opts),
  inpaintImage: (opts) => ipcRenderer.invoke('inpaint-image', opts),
  pdfToImages: (opts) => ipcRenderer.invoke('pdf-to-images', opts),
  imagesToPdf: (opts) => ipcRenderer.invoke('images-to-pdf', opts),
  pdfMerge: (opts) => ipcRenderer.invoke('pdf-merge', opts),
  pdfSplit: (opts) => ipcRenderer.invoke('pdf-split', opts),
  pdfReorder: (opts) => ipcRenderer.invoke('pdf-reorder', opts),
  pdfThumbnails: (input) => ipcRenderer.invoke('pdf-thumbnails', input),
  audiogram: (opts) => ipcRenderer.invoke('audiogram', opts),
  summarizeYoutube: (opts) => ipcRenderer.invoke('summarize-youtube', opts),
  ollamaStatus: () => ipcRenderer.invoke('ollama-status'),
  fileSize: (p) => ipcRenderer.invoke('file-size', p),
  windowMinimize: () => ipcRenderer.invoke('window-minimize'),
  windowMaximizeToggle: () => ipcRenderer.invoke('window-maximize-toggle'),
  windowClose: () => ipcRenderer.invoke('window-close'),
  windowIsMaximized: () => ipcRenderer.invoke('window-is-maximized'),
  onWindowState: (cb) => ipcRenderer.on('window-state', (_, d) => cb(d)),
  copyToClipboard: (text) => ipcRenderer.invoke('copy-to-clipboard', text),
  saveTextFile: (opts) => ipcRenderer.invoke('save-text-file', opts),
  onOcrProgress: (cb) => ipcRenderer.on('ocr-progress', (_, d) => cb(d)),
  onTranscribeProgress: (cb) => ipcRenderer.on('transcribe-progress', (_, d) => cb(d)),
  processAudio: (opts) => ipcRenderer.invoke('process-audio', opts),

  onJobProgress: (cb) => ipcRenderer.on('job-progress', (_, d) => cb(d)),
  onJobLog: (cb) => ipcRenderer.on('job-log', (_, d) => cb(d)),
  onSetupProgress: (cb) => ipcRenderer.on('setup-progress', (_, d) => cb(d)),
  onExtensionDownload: (cb) => ipcRenderer.on('extension-download', (_, d) => cb(d))
});
